version: "3"
services:

  m1:
    build: ./
    image: dcagatay/docker-spark:2.4.7-hadoop3.2.2
    hostname: m1
    environment:
      SPARK_PUBLIC_DNS: "m1"
      SPARK_LOCAL_HOSTNAME: "m1"
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
    # volumes:
    #   - ./conf/master:/conf

  w1:
    image: dcagatay/docker-spark:2.4.7-hadoop3.2.2
    hostname: w1
    depends_on:
      - m1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URI: spark://m1:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      # SPARK_PUBLIC_DNS: localhost
      SPARK_PUBLIC_DNS: "w1"
      SPARK_LOCAL_HOSTNAME: "w1"
    ports:
      - 8881:8881
      - 8081:8081
    # volumes:
    #   - ./conf/worker:/conf

  w2:
    image: dcagatay/docker-spark:2.4.7-hadoop3.2.2
    hostname: w2
    depends_on:
      - m1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URI: spark://m1:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      # SPARK_PUBLIC_DNS: localhost
      SPARK_PUBLIC_DNS: "w2"
      SPARK_LOCAL_HOSTNAME: "w2"
    ports:
      - 8882:8882
      - 8082:8082
    # volumes:
    #   - ./conf/worker:/conf
